spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/loandb
    username: root
    password: mukul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: LOAN-SERVICE
eureka:
  client:
   service-url:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      deafultZone:http://localhost:8761/eureka
server:
  port: 9093