server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/authdb
    username: root
    password: mukul
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        deafultZone:  http://localhost:8761/eureka
jwt:
   secret: bankSecretKeybankSecretKeybankSecretKey123
   expiration: 3600000		