spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/accountdb
    username: root
    password: mukul
  application:
    name: ACCOUNT-SERVICE	
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka
server:
  port: 9092